import type { Character, ModCategory } from '../types/mod.types';

// App version (synchronized with package.json)
export const APP_VERSION = '6.6.1';

// All Marvel Rivals characters in alphabetical order
export const ALL_CHARACTERS: Character[] = [
  'All Characters',
  'Adam Warlock',
  'Angela',
  'Black Panther',
  'Black Widow',
  'Black Cat',
  'Blade',
  'Captain America',
  'Cloak and Dagger',
  'Cyclops',
  'Daredevil',
  'Deadpool',
  'Devil Dinosaur',
  'Doctor Strange',
  'Elsa Bloodstone',
  'Emma Frost',
  'Gambit',
  'Groot',
  'Hawkeye',
  'Hela',
  'Hulk',
  'Human Torch',
  'Invisible Woman',
  'Iron Fist',
  'Iron Man',
  'Jeff the Land Shark',
  'Loki',
  'Luna Snow',
  'Magik',
  'Magneto',
  'Mantis',
  'Mister Fantastic',
  'Moon Knight',
  'Namor',
  'Peni Parker',
  'Phoenix',
  'Psylocke',
  'Rocket Raccoon',
  'Rogue',
  'Scarlet Witch',
  'Spider-Man',
  'Squirrel Girl',
  'Star-Lord',
  'Storm',
  'The Punisher',
  'The Thing',
  'Thor',
  'Ultron',
  'Venom',
  'Winter Soldier',
  'White Fox',
  'Wolverine',
];

// Mod categories in display order
export const MOD_CATEGORIES: ModCategory[] = ['UI', 'Audio', 'Skins', 'Gameplay'];
